# Generated by Django 5.0 on 2025-06-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='offer_message',
            field=models.CharField(blank=True, default='Sports Shop', max_length=300, null=True),
        ),
    ]
