# Generated by Django 5.0 on 2025-06-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_siteconfiguration_offer_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='offer_message',
            field=models.CharField(blank=True, default='Welcome to SportsHub!', max_length=300, null=True),
        ),
    ]
