# Generated by Django 5.0 on 2025-05-14 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomJerseyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('name_on_jersey', models.CharField(max_length=100)),
                ('jersey_number', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=5)),
                ('primary_color', models.CharField(max_length=50)),
                ('secondary_color', models.CharField(blank=True, max_length=50)),
                ('team_logo', models.ImageField(blank=True, upload_to='custom_jerseys/logos/')),
                ('design_preferences', models.TextField(blank=True)),
                ('reference_image', models.ImageField(blank=True, upload_to='custom_jerseys/references/')),
                ('status', models.CharField(choices=[('P', 'Pending Approval'), ('A', 'Approved'), ('D', 'In Design'), ('PR', 'In Production'), ('S', 'Shipped'), ('C', 'Completed'), ('R', 'Rejected')], default='P', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
