# Generated by Django 5.0 on 2025-06-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_jerseys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customjerseyorder',
            name='reference_image_back',
            field=models.ImageField(blank=True, upload_to='custom_jerseys/references/'),
        ),
    ]
